### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by aguerere**

### CODE REVIEW

**Comment by albertoguerere** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://aa93ccb3.ngrok.io/job/auth0-angularjs2-systemjs-sample/9/

**Comment by albertoguerere** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://aa93ccb3.ngrok.io/job/auth0-angularjs2-systemjs-sample/10/

**Comment by aguerere** [comment]
test this please

**Comment by albertoguerere** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://aa93ccb3.ngrok.io/job/auth0-angularjs2-systemjs-sample/11/

**Comment by aguerere** [comment]
test this please

**Comment by aguerere** [comment]
test this please

**Comment by albertoguerere** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://aa93ccb3.ngrok.io/job/auth0-angularjs2-systemjs-sample/12/

**Comment by aguerere** [comment]
test this please

**Comment by albertoguerere** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://aa93ccb3.ngrok.io/job/auth0-angularjs2-systemjs-sample/13/
Build successful

**Comment by aguerere** [comment]
test this please

**Comment by albertoguerere** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://aa93ccb3.ngrok.io/job/auth0-angularjs2-systemjs-sample/14/
Build failure

**Comment by albertoguerere** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://aa93ccb3.ngrok.io/job/auth0-angularjs2-systemjs-sample/15/
Build failure

**Comment by albertoguerere** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://aa93ccb3.ngrok.io/job/auth0-angularjs2-systemjs-sample/16/
Build failure

**Comment by albertoguerere** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://aa93ccb3.ngrok.io/job/auth0-angularjs2-systemjs-sample/17/
Build successful

**Comment by aguerere** [comment]
test this please

**Comment by aguerere** [comment]
test this please

**Comment by aguerere** [comment]
test this please

**Pull request closed without merging**
